# Generated by Django 2.2.6 on 2019-11-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memory',
        ),
    ]
