# Generated by Django 2.2.6 on 2019-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='militarydb',
            name='test',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
