# Generated by Django 2.2.6 on 2019-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
