# Generated by Django 2.2.6 on 2019-11-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdb',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentdb',
            name='student_number',
        ),
    ]
