# Generated by Django 2.2.6 on 2019-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20191111_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='age',
            field=models.PositiveSmallIntegerField(default=1111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdb',
            name='first_name',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdb',
            name='last_name',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdb',
            name='student_number',
            field=models.PositiveSmallIntegerField(default=1111),
            preserve_default=False,
        ),
    ]
